version: '3.8'

services:
  fastapi:
    build: ./fast-api
    ports:
      - "8000:8000"
    env_file:
      - ${ENV_FILE:-.env.local}
    networks:
      - mynetwork

  worker:
    build: ./worker
    env_file:
      - ${ENV_FILE:-.env.local}
    networks:
      - mynetwork

networks:
  mynetwork:
