version: '3.8'

services:
  db:
    image: postgres
    environment:
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    networks:
      - mynetwork

  fastapi:
    build: ./fast-api
    ports:
      - "8000:8000"
    env_file:
      - ${ENV_FILE:-.env.local}
    depends_on:
      - db
    networks:
      - mynetwork

  worker:
    build: ./worker
    env_file:
      - ${ENV_FILE:-.env.local}
    depends_on:
      - db
    networks:
      - mynetwork

networks:
  mynetwork:
